### PR TITLE
build arm64 darwin binaries

### PR DESCRIPTION
**Pull request by upodroid**
# Changes

- :gift: Build darwin binaries

/kind enhancement

Fixes #

**Release Note**

```release-note
kn-operator now has a binary for M1 macs (darwin-arm64)
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by dprotaso** [comment]
I don't have any context here

/assign @houshengbo 
/unassign @dprotaso

**Comment by dsimansk** [comment]
@upodroid I've opened the following PR #284 to fix E2E error in the setup. If you can get to it maybe and we can unblock this one as well. Thx!

**Pull request merged**
