### PR TITLE
Fix Istio setup in e2e tests

### PR DESCRIPTION
**Pull request by dsimansk**
# Changes

- Refactor Istio setup to follow the common pattern from serving and client repos.

/kind <kind>

Fixes #

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by dsimansk** [comment]
Fixes failed integration runs like:
https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-sandbox_kn-plugin-operator/270/integration-tests_kn-plugin-operator_main/1648679217132474368#1:build-log.txt%3A705-706

**Comment by dsimansk** [comment]
This should fix e2e tests before release, PTAL anyone from the list would be nice. Thanks! :)

/cc @rhuss @vyasgun @houshengbo 
/cc @knative-sandbox/knative-release-leads

**Review by upodroid — APPROVED** [review]
LGTM

Thanks

**Comment by dsimansk** [comment]
There's probably a bit more going on the operator side. I'll try to take a look there first.

**Review by upodroid — COMMENTED** [review]
/hold

**Comment by dsimansk** [comment]
@upodroid fyi I've opened operator issue, because the root cause is related to the recent config paths refactor. https://github.com/knative/operator/issues/1416

**Comment by dsimansk** [comment]
IMO it will be fixed on the operator side.

**Comment by upodroid** [comment]
Cancel the hold if you are ready.

**Comment by houshengbo** [comment]
Operator needs to fix it.

**Comment by dsimansk** [comment]
@houshengbo my change is not necessary. The Istio setup is not an issue. Pls let me know if you want to keep using `istioctl` or land this common steps from Serving and Client.

**Pull request closed without merging**
